version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(dev): "
    open-pull-requests-limit: 10
    reviewers:
      - AdmiringWorm
    labels:
      - dependencies
      - javascript
    versioning-strategy: increase
