version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true

branches:
  # Blacklist
  except:
    - /dependabot\/.*/
    - ci/travis

image:
  - macOS
  - Ubuntu
  - Visual Studio 2015

matrix:
  fast_finish: true

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - nodejs_version: "10"

stack: node %nodejs_version%

for:
  - matrix:
      only:
        - image: macos
    environment:
      DOTNET_ROOT: "/Users/appveyor/.dotnet"

install:
  - ps: Install-Product node $env:nodejs_version
  - sh: if [ "$CI_MACOS" ]; then brew install yarn; export PATH="$PATH:/Users/appveyor/.dotnet/tools" ; fi
  - sh: export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - dotnet tool install --global codecov.tool

build_script:
  - pwsh: ./build.ps1 --build

test_script:
  - pwsh: ./build.ps1 --test

on_success:
  - codecov --env 'nodejs_version APPVEYOR_BUILD_WORKER_IMAGE' --file "coverage/clover.xml coverage/coverage-final.json coverage/lcov.info"

cache:
  - "node_modules -> package.json,yarn.lock"

artifacts:
  - path: "*.tgz"
    name: npm package
