version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true

image:
  - Ubuntu
  - Visual Studio 2015

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"

stack: node %nodejs_version%

install:
  - sh: export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - dotnet tool install --global codecov.tool
  - yarn global add codacy-coverage

build_script:
  - pwsh: ./build.ps1 --build

test_script:
  - pwsh: ./build.ps1 --test

on_success:
  - codecov --env nodejs_version,APPVEYOR_BUILD_WORKER_IMAGE --file "coverage/clover.xml coverage/coverage-final.json coverage/lcov.info"
  - sh: cat coverage/lcov.info | codacy-coverage --language typescript
  - cmd: codacy-coverage --language typescript < coverage/lcov.info

cache:
  - "node_modules -> package.json,yarn.lock"
