version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true

image:
  - Ubuntu
#  - Visual Studio 2015

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
#    - nodejs_version: "8"
    - nodejs_version: "10"
#    - nodejs_version: "12"

stack: node %nodejs_version%

install:
  - dotnet tool install --global codecov.tool
  - yarn install

build_script:
  - yarn build

test_script:
  - yarn test --coverage --ci

on_success:
  - codecov --env nodejs_version --file "coverage/clover.xml coverage/coverage-final.json coverage/lcov.info"
  - yarn pack

cache:
  - "node_modules -> package.json,yarn.lock,"
