language: node_js
node_js:
    - v12
    - v10
    - v8

before_install:
    - yarn global add codecov

script:
    - yarn build
    - yarn test --coverage && codecov -e TRAVIS_NODE_VERSION

cache: yarn
