os:
  - linux
  - osx

language: node_js
node_js:
  - v8
  - v10
  - v12

branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
    - ci/travis

before_script: export PATH="$(yarn global bin):$PATH"

script:
  - ./build.sh --build --test
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

cache: yarn

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: v10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release --ci
