version: "{build}"
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true

image:
  - Ubuntu
  - Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

stack: node %nodejs_version%

install:
  - ps: Install-Product $env:nodejs_version
  - yarn global add codecov
  - yarn install

build_script:
  - yarn build

test_script:
  - yarn test --coverage
  - codecov -e nodejs_version

cache:
  - "node_modules -> package.json,yarn.lock"
