image:
  - Ubuntu
  - Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/

matrix:
  fast_finish: true

test: off
build: off

build_script:
  - pwsh: ./build.ps1 --target=CI

cache:
  - "tools -> build.cake,.config/dotnet-tools.json"
